- name: add new Nginx root configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  tags: ['nginx', 'nginx-config', 'config']

- name: stop the nginx service
  service:
    name: nginx
    enabled: yes
    state: stopped
    # expecting new site config
  tags: ['nginx', 'nginx-config', 'config']
