- name: Install certbot
  apt:
    name: certbot
    state: latest

- name: execute certbot
  shell: |
    certbot  certonly --non-interactive \
      --agree-tos --expand --webroot --test-cert \
      -m "{{ admin_email }}"  --domain  {{ server_name }} \
      --webroot-path "/var/www/letsencrypt/"
