- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: setup a directory for wellknow verification
  file:
    path: /var/www/letsencrypt/.well-known/acme-challenge
    state: directory
    recurse: true

# we'll acquire the cert with this configuration first.
- name: add site configuration for cerbot/well-known authentication
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default

- name: restart the nginx service
  service:
    name: nginx
    enabled: yes
    state: restarted
