- name: setup a directory to serve content from
  file:
    path: /home/shey/content
    state: directory
    recurse: true

- name: add site configuration for http service
  template:
    src: simple.j2
    dest: /etc/nginx/sites-available/simple
    owner: www-data
    group: www-data

- name: enable app site
  file:
    src: /etc/nginx/sites-available/simple
    dest: /etc/nginx/sites-enabled/simple
    owner: www-data
    group: www-data
    state: link

- name: add simple http service
  template:
    src: simple.service.j2
    dest: "/etc/systemd/system/simple.service"
    owner: root
    group: root
    mode: 0644

- name: start/enable simple http service
  systemd:
    name: simple
    daemon_reload: yes
    state: started
    enabled: yes

- name: restart nginx confg
  service:
    name: nginx
    state: restarted
