- name: Nginx server with Certbot for SSL
  hosts: webservers
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: custom-users, tags: ['users'] }
    - { role: swap, tags: ['swap'] }
    - { role: nginx-certbot, tags: ['nginx'] }
    - { role: nginx-reverse-proxy, tags: ['nginx'] }
    - { role: simple-http-server, tags: ['simple-http-server'] }
